#!/usr/bin/env bash

# create our vpc
VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" --region us-east-2 --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' --query Vpc.VpcId --output text)
echo $VPC_ID
# create an IGW

# explicitly associate subnet
# 
# 
# add a route for our RT to our IGW