#!/usr/bin/env bash
echo "== deletes objects"
#exit if any command returns a non-zero status
set -e

#checking for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name1"
    exit 1
fi

BUCKET_NAME=$1
$(aws s3api list-objects-v2 --bucket $BUCKET_NAME)

aws s3api delete-objects --bucket $BUCKET_NAME