#!/usr/bin/env bash
echo "== sync"
#exit if any command returns a non-zero status
set -e

#checking for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name1"
    exit 1
fi

#checking for filename prefix 
if [ -z "$1" ]; then
    echo "There needs to be a file name prefix eg. ./bucket my-bucket-name1 my-filename-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

#storage location of files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove folder if it already exits
rm -r $OUTPUT_DIR

#create output folder
mkdir -p $OUTPUT_DIR



#generates between 5 and 10
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
        #generates filename
        FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

        # generates random data to write into file
        dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files